version: '3.1'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: nses
      POSTGRES_PASSWORD: superpassword
      POSTGRES_DB: nses
    volumes:
      - /data/nses/postgresql:/var/lib/postgresql
    ports:
      - 5432:5432
    command: -c 'log_statement=all'
  adminer:
    image: adminer
    ports:
      - 8080:8080
